# Demo to prove that gcp-store is valid for external secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-proxy-tls
  namespace: kong
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store               # name of the SecretStore (or kind specified)
  target:
    name: kong-proxy-tls    # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kong-proxy-tls     # name of the GCPSM secret key
      decodingStrategy: Auto